# fly.toml app configuration file generated for kazumi-riku-snowy-cloud-5149 on 2025-05-03T22:34:42+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kazumi-riku-snowy-cloud-5149'
primary_region = 'sin'

[build]


[processes]
  app = "node index.js"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
